name: projeto-redes2

services:
  dns:
    image: coredns/coredns:1.11.3
    container_name: dns
    command: -conf /etc/coredns/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile:ro
    networks:
      - projeto-redes2-net
    restart: unless-stopped

  gateway:
    image: nginx:1.27-alpine
    container_name: projeto-redes2-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tenant1
      - tenant2
    networks:
      - projeto-redes2-net
    restart: unless-stopped

  tenant1:
    build:
      context: ./tenants
      dockerfile: Dockerfile
      args:
        TENANT_DIR: tenant1
    image: projeto-redes2/tenant1:latest
    container_name: projeto-redes2-tenant1
    expose:
      - "80"
    networks:
      - projeto-redes2-net
    restart: unless-stopped

  tenant2:
    build:
      context: ./tenants
      dockerfile: Dockerfile
      args:
        TENANT_DIR: tenant2
    image: projeto-redes2/tenant2:latest
    container_name: projeto-redes2-tenant2
    expose:
      - "80"
    networks:
      - projeto-redes2-net
    restart: unless-stopped

networks:
  projeto-redes2-net:
    name: projeto-redes2-net
    driver: bridge
