events {}

http {
    upstream tenant1_backend {
        server tenant1:80;
    }

    upstream tenant2_backend {
        server tenant2:80;
    }

    server {
        listen 80 default_server;
        server_name _;

        return 404 "Tenant nao encontrado. Use tenant1.redes2.local ou tenant2.redes2.local.\n";
    }

    server {
        listen 80;
        server_name tenant1.redes2.local;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://tenant1_backend;
        }
    }

    server {
        listen 80;
        server_name tenant2.redes2.local;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://tenant2_backend;
        }
    }
}
