events {}

http {
    server {
        listen 80;

        server_name tenant1.local;

        location / {
            proxy_pass http://tenant1:7000;
        }
    }

    server {
        listen 80;

        server_name tenant2.local;

        location / {
            proxy_pass http://tenant2:7000;
        }
    }
}